title: Ivan Majic # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I have Geodesy and Geoinformatics background and am obtaining a PhD in Geomatics
  from The University of Melbourne. In my research, I specialise in Spatial Data Quality and Topological relations.
  My reserach has been published in renowned journals in the fields of GIScience, Spatial Databases, Positioning,
  Urbanism, and Smart Cities.
  I have expertise in Spatial Databases and Programming in GIS, and work experience in QGIS plugin development,
  Linux server administration, teaching, marketing data analysis, and land surveying.
  <br><br>
  My hobbies involve, but are not limited to:
  - boxing
  - baking sourdough breads and pizzas
  - cycling (commuter)
  - brewing delicious espressos
  - photography
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-171527866-1 # your Google Analytics tracking ID here
